### ISSUE TITLE
Deployed demo site doesn't work 

### ISSUE THREAD

**Issue by IannisIP** [oracle/cloudtestdrive#128]
After following the tutorial, the using the ip to acces the demo deployed site doesn't work. Build runs ok.
[2021-04-25 13:02:15] + kubectl get pods
[2021-04-25 13:02:18] NAME                    READY   STATUS             RESTARTS   AGE
[2021-04-25 13:02:18] atp2-75ffb788cc-svsct   0/1     ImagePullBackOff   0          6s

Pod description

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  25m                   default-scheduler  Successfully assigned default/atp2-75ffb788cc-svsct to 10.0.10.154
  Normal   Pulling    24m (x4 over 25m)     kubelet            Pulling image "fra.ocir.io/fri8nesdgloc/atpdocker_pi/atp01:latest"
  Warning  Failed     24m (x4 over 25m)     kubelet            Failed to pull image "fra.ocir.io/fri8nesdgloc/atpdocker_pi/atp01:latest": rpc error: code = Unknown desc = Get "https://fra.ocir.io/v2/fri8nesdgloc/atpdocker_pi/atp01/manifests/latest": unknown: Unauthorized
  Warning  Failed     24m (x4 over 25m)     kubelet            Error: ErrImagePull
  Warning  Failed     5m43s (x87 over 25m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    36s (x110 over 25m)   kubelet            Back-off pulling image "fra.ocir.io/fri8nesdgloc/atpdocker_pi/atp01:latest"

https://github.com/oracle/cloudtestdrive/blob/master/AppDev/ATP-OKE/LabGuide670DeployDocker.md

**Comment by janleemans** [comment]
Hello Iannis, your error seems to indicate you do not have authorization to pull the image from the private docker repo.  This means you probably did not set up the secret called "<your-initials>-ocirsecret" correctly, or you did not change the name of the secret containing your initials in the "atp2.yaml" file. (the parameter imagepullsecret).  
Make sure to explicitly delete the secret before trying to recreate it, otherwise your changes might not be taken into account.
Example command to set the secret : kubectl create secret docker-registry jle-ocirsecret --docker-server=fra.ocir.io --docker-username='epqldntjs/oracleidentitycloudservice/ppan@oracle.com' --docker-password='k]j64r{1sJSSF-;)K8' --docker-email='jdoe@acme.com'
Please note this example assumes you are using a SSO user via the Oracle cloud Identity service.  If you are using a direct login user you should not use the "oracleidentitycloudservice" part in the username.
